spring:
  profiles:
    active: dev

  application:
    name: TacoCloud
  thymeleaf.cache: false
  datasource:
    generate-unique-name: false
    name: tacoCloud
    username: acdevs
    password: 4444

  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer

taco:
  orders:
    pageSize: 10

# embedded server and key certificates
server:
  port: 8080
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 10s
    threads:
      max: 10
      min-spare: 5
#  ssl:
#    key-store: mykey.jks
#    key-password: tooshort
#    key-store-password: tooshort

# debug logging
logging:
  file:
    path: /logs
    name: TacoCloud.log
  level:
    root: info



---

