spring:
  config:
    import: optional:secrets.yml

  application:
    name: TacoAdminClient
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - email
              - profile
              - openid

          taco-admin-client:
            provider: tacoCloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:9090/login/oauth2/code/taco-admin-client"
            scope:
              - writeIngredients
              - deleteIngredients
              - viewIngredients
              - openid
        provider:
          tacoCloud:
            issuer-uri: http://127.0.0.1:9000

server:
  port: 9090
