spring:
  profiles:
    active: dev

  application:
    name: TacoCloud
  thymeleaf.cache: false
  datasource:
    generate-unique-name: false
    name: tacoCloud
    username: acdevs
    password: 4444

  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks

  rabbitmq:
    host: localhost
    port: 5672
    username: acdevs
    password: 4444
    template:
      exchange: tacocloud.orders.exchange
      routing-key: tacocloud.orders.routing.key

# custom properties
taco:
  orders:
    pageSize: 10

# embedded server and key certificates
server:
  port: 8080
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 10s
    threads:
      max: 10
      min-spare: 5
#  ssl:
#    key-store: mykey.jks
#    key-password: tooshort
#    key-store-password: tooshort

# debug logging
logging:
  file:
    path: /logs
    name: TacoCloud.log
  level:
    root: info

# actuator endpoints
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: threadDump, heapDump, shutdown
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true

info:
  name: TacoCloud
  description: Tacos at your fingertips 🌮
  contact:
    phone: +91 9335273000
    email: support@tacocloud.com


