CREATE TABLE IF NOT EXISTS INGREDIENT (
    ID VARCHAR(4) NOT NULL PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL,
    TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO_ORDER (
    ID IDENTITY PRIMARY KEY,
    DELIVERY_NAME VARCHAR(25) NOT NULL,
    DELIVERY_ZIP VARCHAR(10) NOT NULL,
    UPI_ID VARCHAR(20) NOT NULL,
    PLACED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);
