CREATE TABLE IF NOT EXISTS INGREDIENT (
    ID VARCHAR(4) NOT NULL PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL,
    TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO_ORDER (
    ID IDENTITY PRIMARY KEY,
    DELIVERY_NAME VARCHAR(25) NOT NULL,
    DELIVERY_ZIP VARCHAR(10) NOT NULL,
    UPI_ID VARCHAR(20) NOT NULL,
    PLACED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    TACO_ORDER BIGINT NOT NULL,
    TACO_ORDER_KEY BIGINT NOT NULL,
    FOREIGN KEY (TACO_ORDER) REFERENCES TACO_ORDER(ID)
);

CREATE TABLE IF NOT EXISTS INGREDIENT_REF (
    TACO BIGINT NOT NULL,
    TACO_KEY BIGINT NOT NULL,
    INGREDIENT VARCHAR(4) NOT NULL,
    FOREIGN KEY (INGREDIENT) REFERENCES INGREDIENT(ID),
    FOREIGN KEY (TACO) REFERENCES TACO(ID)
);
